### ISSUE TITLE
Chore: Edit down `README.md` and update to latest Tech Stack

### ISSUE THREAD

**Issue by nelsonic** [dwyl/book#93]
At present the initial [**`README.md`**](https://github.com/dwyl/book/tree/5260321ad00b8a09a7a59287cdec348f357f3b9f) of this repo is a bit "ramble-y" ... 🙃 
I think we could/should _either_ trim it down by at least _half_ ✂️ 
***or*** even re-write it completely to joint point people to the `book`: https://dwyl.github.io/book 💭 

# Todo

+ [ ] Decide if there is anything in the _current_ [**`README.md`**](https://github.com/dwyl/book/tree/5260321ad00b8a09a7a59287cdec348f357f3b9f) that is worth keeping.
+ [ ] Re-work the `README.md` so that it gives _just_ enough info about what we're doing.
+ [ ] Then link to the book.
+ [ ] Question: should we host the book on a subdomain e.g: `book.dwyl.com` for SEO? 💭
